### ISSUE TITLE
Send To Owners rounding tie resolution consider alternatives to Bitcoin Address

### ISSUE THREAD

**Issue by msgilligan** [mastercoin-MSC/spec#300]
Using Bitcoin address for tie resolution in Send To Owners distribution rounding could conceivable result in undesired behavior.

1. Regular addresses ('1xxxx...') would be given precedence over P2SH (multisig, '3xxxx...') addresses, so this could penalize use of multisig.

2. Users may become tempted to create vanity addresses that come first in lexicographic order.

(Granted these incentives are only likely to be significant in a property that becomes valuable enough that a single "willet" is economically significant)

Possible solutions include:

1. Ignoring the 'version' byte/character at the beginning of the address for tie-resolution ordering. (This will at least stop penalizing multisig)

2. Finding another, less-gameable factor for resolution, such as age of the oldest UTXO on the address. (I realize that some of these may be harder to implement than sorting by address.)

**Comment by marv-engine** [comment]
Another possible solution is to do a hash on the address concatenated with some attribute of a (randomly selected) transaction the address was involved in and/or a subset of the bytes in the address of that attribute.

Or, we could just assign a random number to each address and then order by the random numbers.

**Comment by msgilligan** [comment]
We can't maintain consensus if we us anything random. Ideally we need something deterministic that can't easily be gamed.

**Comment by dexX7** [comment]
I noticed this, too, while testing. However, I wouldn't go so far and change something here, it because affects only those with the same number of tokens, but it increases the complexity.

Nevertheless, a potential solution could be to apply f(address, total_number_of_recipients) where f is a function like multiplication (e.g. actual_recipient = address_as_number * total_number_of_recipients).

Keep in mind: the address *is* already a hash (base58 encoded).

**Comment by dacoinminster** [comment]
We need to use something deterministic, but not knowable in advance, like
the hash of the block that the send-to-owners tx gets put in :)

**Comment by msgilligan** [comment]
Yes, @dacoinminster that sounds like it should work!  "Not knowable in advance" =~ "Not easily gamed".

**Comment by dexX7** [comment]
> hash of the block

That's actually not that great when it comes to block reorganizations.

**Comment by msgilligan** [comment]
Good point, @dexX7. Is there something else "deterministic, but not knowable in advance" that we can use? The hash of the STO transaction itself?

**Comment by CraigSellars** [comment]
This issue is a fringe case.  We can review this (or re-open it) for a subsequent build.
